/**
 * BiDi (bidirectional text) helpers.
 *
 * The Unicode Bidirectional Algorithm resolves neutral characters (spaces,
 * punctuation, brackets, arrows) by looking at the strong characters around
 * them. In a mixed English/Persian line that means punctuation between two
 * scripts gets pulled to the "wrong" side and separate phrases visually merge
 * into one reversed run — the text is technically correct but unreadable.
 *
 * The fix is isolation: wrap every run of the *opposite* direction in its own
 * bidi isolate (`<bdi>` in HTML, a `unicode-bidi: isolate` mark in CodeMirror).
 * An isolate counts as a single neutral object to the surrounding text, so the
 * runs stay in the order the author typed them while each one is still ordered
 * correctly inside itself.
 */

// Arabic, Hebrew, Persian, Thaana, Syriac, N'Ko, Arabic presentation forms.
export const RTL_CHAR =
  /[\u0590-\u05FF\u0600-\u06FF\u0700-\u074F\u0780-\u07BF\u0860-\u086F\u08A0-\u08FF\uFB1D-\uFDFF\uFE70-\uFEFF]/;
// Latin, Greek, Cyrillic and friends.
export const LTR_CHAR = /[A-Za-z\u00C0-\u02AF\u0370-\u03FF\u0400-\u04FF\u1E00-\u1EFF]/;

const DIGIT = /[0-9]/;

/**
 * Arrows and bullets: never part of a word, always a structural separator.
 */
const HARD_SEPARATOR = /[\u2190-\u21FF\u27F0-\u27FF\u2900-\u297F\u2B00-\u2B11\u2022]/;
/**
 * Separators only when they stand alone between spaces. Spaced, "A / B / C" is
 * a list the author reads left-to-right; unspaced it is one compound term
 * (Persian words joined by a slash) that must stay a single run.
 */
const SOFT_SEPARATOR = /[/\\|>+]/;
const SPACE = /\s/;

function isSeparator(text, i) {
  const ch = text[i];
  if (HARD_SEPARATOR.test(ch)) return true;
  if (!SOFT_SEPARATOR.test(ch)) return false;
  // Standalone only: " / " separates, "a/b" does not.
  const before = text[i - 1];
  const after = text[i + 1];
  return (before === undefined || SPACE.test(before)) && (after === undefined || SPACE.test(after));
}

function charDirection(ch) {
  if (RTL_CHAR.test(ch)) return "rtl";
  if (LTR_CHAR.test(ch)) return "ltr";
  return null;
}

/**
 * Base direction of a string, using the first-strong-character heuristic from
 * the Unicode Bidi Algorithm (rules P2/P3) — the same rule `dir="auto"` uses.
 */
export function detectBaseDirection(text) {
  for (let i = 0; i < text.length; i++) {
    const dir = charDirection(text[i]);
    if (dir) return dir;
  }
  return "ltr";
}

/** Back-compat alias used by the CodeMirror per-line direction plugin. */
export function isRTLLine(text) {
  return detectBaseDirection(text) === "rtl";
}

/**
 * Find the runs that need isolating in `text`, given the block's base
 * direction. Returns `[{ start, end }]` character ranges (end exclusive),
 * covering every maximal run of the direction opposite to `baseDir`.
 *
 * Interior neutrals (spaces, commas, brackets) stay inside a run so real
 * sentences are not shredded into per-word isolates, but leading/trailing
 * neutrals are trimmed off so they resolve against the base direction.
 *
 * One asymmetry: inside an LTR block, a separator symbol between two RTL runs
 * is almost always structural — a breadcrumb, flow arrow or slash-separated
 * list the author reads left-to-right — so it ends the run. Inside an RTL
 * block the reverse is not true: a contiguous Latin stretch including its
 * separators is a single foreign phrase and must stay glued together.
 */
export function findIsolateRuns(text, baseDir = "ltr") {
  const target = baseDir === "rtl" ? "ltr" : "rtl";
  const splitOnSeparators = baseDir === "ltr";
  const runs = [];

  let start = -1; // index of the first strong char of the open run
  let end = -1; // one past the last strong (or attached weak) char

  const close = () => {
    if (start !== -1) runs.push({ start, end });
    start = -1;
    end = -1;
  };

  for (let i = 0; i < text.length; i++) {
    const ch = text[i];
    const dir = charDirection(ch);

    if (dir === target) {
      if (start === -1) start = i;
      end = i + 1;
    } else if (dir) {
      // A strong character of the base direction ends the run.
      close();
    } else if (start !== -1 && DIGIT.test(ch)) {
      // Digits after a strong char belong to the run ("قیمت 300").
      end = i + 1;
    } else if (start !== -1 && splitOnSeparators && isSeparator(text, i)) {
      close();
    }
    // Other neutrals keep the run open; `end` trims them if nothing follows.
  }
  close();

  return runs;
}

// Elements whose text must keep its literal order, or whose contents are
// generated by another renderer (KaTeX, Mermaid, highlight.js).
const SKIP_TAGS = new Set([
  "PRE",
  "CODE",
  "SCRIPT",
  "STYLE",
  "TEXTAREA",
  "BDI",
  "BDO",
  "SVG",
  "MATH",
]);
const SKIP_CLASSES = ["katex", "mermaid", "mermaid-wrapper", "code-block-wrapper"];

function isSkipped(el) {
  for (let node = el; node && node.nodeType === 1; node = node.parentElement) {
    if (SKIP_TAGS.has(node.tagName)) return true;
    for (const cls of SKIP_CLASSES) {
      if (node.classList?.contains(cls)) return true;
    }
  }
  return false;
}

function resolvedDirection(el, cache) {
  if (cache.has(el)) return cache.get(el);
  // `dir="auto"` is resolved by the browser, so the computed style is the
  // block's real base direction — no need to re-run the heuristic here.
  let dir = "ltr";
  try {
    dir = window.getComputedStyle(el).direction === "rtl" ? "rtl" : "ltr";
  } catch {
    dir = "ltr";
  }
  cache.set(el, dir);
  return dir;
}

/**
 * Wrap opposite-direction runs of every text node under `root` in `<bdi>`.
 * Idempotent per render: the preview HTML is regenerated wholesale, and
 * existing `<bdi>` elements are skipped.
 */
export function isolateBidiRuns(root) {
  if (!root || typeof document === "undefined") return;
  // Cheap bail-out for the common case: a note with no RTL characters at all.
  if (!RTL_CHAR.test(root.textContent || "")) return;

  const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT);
  const dirCache = new Map();
  const pending = [];

  // Collect first, mutate after: inserting <bdi> changes how `dir="auto"`
  // resolves on the ancestors, so all base directions must be read up front.
  let node = walker.nextNode();
  while (node) {
    const text = node.nodeValue;
    const parent = node.parentElement;
    if (text && text.trim() && parent && !isSkipped(parent)) {
      const baseDir = resolvedDirection(parent, dirCache);
      const runs = findIsolateRuns(text, baseDir);
      // A run covering the whole node is already isolated by the element.
      if (
        runs.length &&
        !(runs.length === 1 && runs[0].start === 0 && runs[0].end === text.length)
      ) {
        pending.push({ node, runs });
      }
    }
    node = walker.nextNode();
  }

  for (const { node: textNode, runs } of pending) {
    const text = textNode.nodeValue;
    const frag = document.createDocumentFragment();
    let pos = 0;
    for (const { start, end } of runs) {
      if (start > pos) frag.appendChild(document.createTextNode(text.slice(pos, start)));
      const bdi = document.createElement("bdi");
      bdi.textContent = text.slice(start, end);
      frag.appendChild(bdi);
      pos = end;
    }
    if (pos < text.length) frag.appendChild(document.createTextNode(text.slice(pos)));
    textNode.parentNode?.replaceChild(frag, textNode);
  }
}
